[theme]
primaryColor="#546A7B"
backgroundColor="#393D3F"
secondaryBackgroundColor="#C6C5B9"
textColor="#FDFDFF"

[client]
toolbar = "minimal"

As I stated a number of times,
47 65 6E 67 68 69 73
17:50:23
There's a number of things that you can control.
47 65 6E 67 68 69 73
17:50:27
there's a whole lot of things that you cannot control.
47 65 6E 67 68 69 73
17:50:31
The one thing that I would suggest that you, you know, put a little bit of time and effort into is to simply
47 65 6E 67 68 69 73
17:50:37
keep getting better at something.
For the past few months, you have
experience and endure an entire array
47 65 6E 67 68 69 73
17:50:45
of different scales and techniques and coding and all of that.
47 65 6E 67 68 69 73
17:50:49
Now is the time, as the court comes to an end.
47 65 6E 67 68 69 73
17:50:52
that you take a little bit of time for yourself,
47 65 6E 67 68 69 73
17:50:55
assess what you have, don't start taking notes, obviously.
47 65 6E 67 68 69 73
17:50:59
Right? But now you choose, okay, I'm gonna spend the next month, the next two months, whatever the case might be.
47 65 6E 67 68 69 73
17:51:05
I don't know your situation, but I was…
47 65 6E 67 68 69 73
17:51:07
I would approach it this way.
I would say I want to take the next month or so, and I'm gonna only do SQL.
For instance, and I'm gonna…
47 65 6E 67 68 69 73
17:51:15
get better at SQL, I'm gonna do some practice rounds, I wanna make sure that I understand the basic concepts.
47 65 6E 67 68 69 73
17:51:21
I'm gonna contact…
47 65 6E 67 68 69 73
17:51:25
the professor, I'm gonna be like, hey, can we have a session and have a talk about these questions that I have?
47 65 6E 67 68 69 73
17:51:30
Write those questions down, right?
47 65 6E 67 68 69 73
17:51:32
And continue to get better at… just say at the… at this time, one thing.
And then when you feel confident about that, you add more stuff.

Now, this is the difficult bit.
47 65 6E 67 68 69 73
17:51:42
As you are, for instance, focusing on one specific skill. Let's just say, once again, for the sake of our… for the sake of argument,
47 65 6E 67 68 69 73
17:51:49
just SQL. That doesn't mean that you neglect the other ones.
47 65 6E 67 68 69 73
17:51:52
What does that mean? You simply… I'm gonna dedicate 2 hours a day, 1 hour a day, whatever the case might be,
47 65 6E 67 68 69 73
17:51:57
to really study, focus down, and review SQL.
47 65 6E 67 68 69 73
17:52:00
Once again, just as an example.
47 65 6E 67 68 69 73
17:52:03
But still take the time in the afternoon to go back to your practice, whatever those projects are.
47 65 6E 67 68 69 73
17:52:08
and fine-tune the stuff that you have.
47 65 6E 67 68 69 73
17:52:11
get yourself one of those little notebooks. I have a number of them, because I buy them by the pack.
like, 8x5 little notebooks that you write notes in, or really small stuff.

You are more than welcome to contact me, and I am always ready to start something… to start a new product.
47 65 6E 67 68 69 73
17:53:20
That's my problem, right?
I am going to go dark for a little bit, because I'm gonna be coding in Rust.

Yeah, yeah, yeah, I was like, yo, I chose these three projects because I liked them. For instance, if I were to present,
47 65 6E 67 68 69 73
17:54:57
I like this, you're probably gonna feel really passionate about what I learned here, and I wanted to showcase that I learned to do this, this, and that.
47 65 6E 67 68 69 73
17:55:02
And I plan to continue furthering and fine-tuning those projects, and blah blah blah blah blah.
47 65 6E 67 68 69 73
17:55:07
This is not an official type thing, this is not an interview.
is unlike what you were doing before that was for a grade. This is now you showcasing

This is what I learned. I'm glad I came to this place, or…
that I had the misfortune of having Genghis as an instructor, because that dude is nuts.


rss
The key is never stop learning.
47 65 6E 67 68 69 73
18:04:24
that's… that's… that's the key. Because when you are… when you keep learning, you are forced.
47 65 6E 67 68 69 73
18:04:29
to continue to look out for stuff.
47 65 6E 67 68 69 73
18:04:33
And by looking out for stuff, you're going to be aware of the trends, where are things going, what should I learn next?
47 65 6E 67 68 69 73
18:04:38
How do I do this? And so forth and so on, so…
At the end of the day, the key here is never stop learning.
